module.exports = {
  content: [
    "./src/**/*.{html,js,ts,jsx,tsx}",
    "app/**/*.{ts,tsx}",
    "components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "accents-purple": "var(--accents-purple)",
        accentsblue: "var(--accentsblue)",
        accentsgreen: "var(--accentsgreen)",
        accentsred: "var(--accentsred)",
        accentsyellow: "var(--accentsyellow)",
        brandsprimary: "var(--brandsprimary)",
        brandssecondary: "var(--brandssecondary)",
        brandstertiary: "var(--brandstertiary)",
        "color-primary": "var(--color-primary)",
        "color-text": "var(--color-text)",
        "color-white": "var(--color-white)",
        colorblack: "var(--colorblack)",
        lightsblue: "var(--lightsblue)",
        lightsborder: "var(--lightsborder)",
        lightsgray: "var(--lightsgray)",
        "neutrals-0": "var(--neutrals-0)",
        "neutrals-1-0i": "var(--neutrals-1-0i)",
        "neutrals-100": "var(--neutrals-100)",
        "neutrals-20": "var(--neutrals-20)",
        "neutrals-40": "var(--neutrals-40)",
        "neutrals-60": "var(--neutrals-60)",
        "neutrals-80": "var(--neutrals-80)",
        "other-colorsuntitledborder-dashboard":
          "var(--other-colorsuntitledborder-dashboard)",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        "body-large-regular": "var(--body-large-regular-font-family)",
        "body-large-semibold": "var(--body-large-semibold-font-family)",
        "body-normal-medium": "var(--body-normal-medium-font-family)",
        "body-normal-regular": "var(--body-normal-regular-font-family)",
        "body-normal-semibold": "var(--body-normal-semibold-font-family)",
        "body-small-medium": "var(--body-small-medium-font-family)",
        "body-small-regular": "var(--body-small-regular-font-family)",
        "body-small-semibold": "var(--body-small-semibold-font-family)",
        "body-xlarge-regular": "var(--body-xlarge-regular-font-family)",
        "button-large": "var(--button-large-font-family)",
        "button-normal": "var(--button-normal-font-family)",
        "display-2": "var(--display-2-font-family)",
        "heading-h2": "var(--heading-h2-font-family)",
        "title-large-semibold": "var(--title-large-semibold-font-family)",
        sans: [
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
      },
      boxShadow: {
        shadow: "var(--shadow)",
        "x-border": "var(--x-border)",
        "y-border": "var(--y-border)",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
  },
  plugins: [],
  darkMode: ["class"],
};
